backend:
  name: github
  repo: yourusername/yourrepository  # Replace with your GitHub username and repo
  branch: main  # Or 'master'

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "dreams"
    label: "Dream Meanings"
    folder: ""  # No folder, just individual files
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["Animals", "Places", "Relationships", "Properties"] }
